name: Build and Deploy Playground

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: 'playground/package-lock.json'

      - name: Install Dependencies
        working-directory: ./playground
        run: npm ci

      - name: Build
        working-directory: ./playground
        run: npm run build
